2016-03-09 12:18:25 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Error de Sintaxis en sentencia SQL "CREATE DATABASE[*] IFACTURA"; se esperaba "OR, FORCE, VIEW, ALIAS, SEQUENCE, USER, TRIGGER, ROLE, SCHEMA, CONSTANT, DOMAIN, TYPE, DATATYPE, AGGREGATE, LINKED, MEMORY, CACHED, LOCAL, GLOBAL, TEMP, TEMPORARY, TABLE, PRIMARY, UNIQUE, HASH, SPATIAL, INDEX"
Syntax error in SQL statement "CREATE DATABASE[*] IFACTURA"; expected "OR, FORCE, VIEW, ALIAS, SEQUENCE, USER, TRIGGER, ROLE, SCHEMA, CONSTANT, DOMAIN, TYPE, DATATYPE, AGGREGATE, LINKED, MEMORY, CACHED, LOCAL, GLOBAL, TEMP, TEMPORARY, TABLE, PRIMARY, UNIQUE, HASH, SPATIAL, INDEX"; SQL statement:
CREATE DATABASE IFACTURA [42001-191]
2016-03-09 12:21:08 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Error de Sintaxis en sentencia SQL "CREATE IFACTURA[*].CLIENTE( ID INT AUTO_INCREMENT PRIMARY KEY, NOMBRE VARCHAR(20), APELLIDO VARCHAR(20), DNI VARCHAR(20), E-MAIL VARCHAR(50)) "; se esperaba "OR, FORCE, VIEW, ALIAS, SEQUENCE, USER, TRIGGER, ROLE, SCHEMA, CONSTANT, DOMAIN, TYPE, DATATYPE, AGGREGATE, LINKED, MEMORY, CACHED, LOCAL, GLOBAL, TEMP, TEMPORARY, TABLE, PRIMARY, UNIQUE, HASH, SPATIAL, INDEX"
Syntax error in SQL statement "CREATE IFACTURA[*].CLIENTE( ID INT AUTO_INCREMENT PRIMARY KEY, NOMBRE VARCHAR(20), APELLIDO VARCHAR(20), DNI VARCHAR(20), E-MAIL VARCHAR(50)) "; expected "OR, FORCE, VIEW, ALIAS, SEQUENCE, USER, TRIGGER, ROLE, SCHEMA, CONSTANT, DOMAIN, TYPE, DATATYPE, AGGREGATE, LINKED, MEMORY, CACHED, LOCAL, GLOBAL, TEMP, TEMPORARY, TABLE, PRIMARY, UNIQUE, HASH, SPATIAL, INDEX"; SQL statement:
CREATE ifactura.cliente( ID INT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(20), apellido VARCHAR(20), DNI VARCHAR(20), E-MAIL VARCHAR(50)) [42001-191]
2016-03-09 12:21:34 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Tipo de dato desconocido : "-"
Unknown data type: "-"; SQL statement:
CREATE TABLE ifactura.cliente( ID INT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(20), apellido VARCHAR(20), DNI VARCHAR(20), E-MAIL VARCHAR(50)) [50004-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4059)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3922)
	at org.h2.command.Parser.parseCreateTable(Parser.java:5864)
	at org.h2.command.Parser.parseCreate(Parser.java:4217)
	at org.h2.command.Parser.parsePrepared(Parser.java:360)
	at org.h2.command.Parser.parse(Parser.java:315)
	at org.h2.command.Parser.parse(Parser.java:287)
	at org.h2.command.Parser.prepareCommand(Parser.java:252)
	at org.h2.engine.Session.prepareLocal(Session.java:560)
	at org.h2.engine.Session.prepareCommand(Session.java:501)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1388)
	at org.h2.server.web.WebApp.query(WebApp.java:1061)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1023)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1010)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2016-03-09 12:34:41 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Tabla "CLIENTE" no encontrada
Table "CLIENTE" not found; SQL statement:
SELECT * FROM CLIENTE [42102-191]
2016-03-09 13:19:06 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Schema "INFORMATION_SCHEMA" no puede ser eliminado
Schema "INFORMATION_SCHEMA" cannot be dropped; SQL statement:
DROP SCHEMA INFORMATION_SCHEMA [90090-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.DropSchema.update(DropSchema.java:44)
	at org.h2.command.CommandContainer.update(CommandContainer.java:98)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1388)
	at org.h2.server.web.WebApp.query(WebApp.java:1061)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1023)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1010)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2016-03-09 14:55:03 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Error de Sintaxis en sentencia SQL "INSERT INTO PUBLIC.CLIENTES(NOMBRE, APELLIDO, EDAD, DNI, EMAIL) VALUES
('Mónica', 'Garrido', 22, '12345678A', 'cortesm@dit.upm.es'),
('Alejandro', 'Docasar', 21, '12345678B', 'alejandrod@dit.upm.es'),
('Oscar', 'Vázquez', 21, '12345678C', 'oscarv@dit.upm.es'),
('Carlos', 'Padilla', 21, '12345678D', 'carlosp@dit.upm.es'),
('Héctor', 'Belló', 21, '12345678E', 'hectorb@dit.upm.es'),
('Fátima', 'García', 21, '12345678F', 'fatimag@dit.upm.es')


CREATE[*] CACHED TABLE PUBLIC.TELEFONO(
    ID INTEGER AUTO_INCREMENT NOT NULL,
    COMPAÑIA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    IMPORTE DOUBLE NOT NULL,
    DATOS CONTRATADOS DOUBLE NOT NULL,
    DATOS CONSUMIDOS DOUBLE NOT NULL,
    4G BOOLEAN NOT NULL,
    VOZ CONTRATADA DOUBLE NOT NULL,
    VOZ CONSUMIDA DOUBLE NOT NULL,
    FRANJA VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    CLIENTE INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CLIENTE) REFERENCES PUBLIC.CLIENTES(ID)
)"
Syntax error in SQL statement "INSERT INTO PUBLIC.CLIENTES(NOMBRE, APELLIDO, EDAD, DNI, EMAIL) VALUES
('Mónica', 'Garrido', 22, '12345678A', 'cortesm@dit.upm.es'),
('Alejandro', 'Docasar', 21, '12345678B', 'alejandrod@dit.upm.es'),
('Oscar', 'Vázquez', 21, '12345678C', 'oscarv@dit.upm.es'),
('Carlos', 'Padilla', 21, '12345678D', 'carlosp@dit.upm.es'),
('Héctor', 'Belló', 21, '12345678E', 'hectorb@dit.upm.es'),
('Fátima', 'García', 21, '12345678F', 'fatimag@dit.upm.es')


CREATE[*] CACHED TABLE PUBLIC.TELEFONO(
    ID INTEGER AUTO_INCREMENT NOT NULL,
    COMPAÑIA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    IMPORTE DOUBLE NOT NULL,
    DATOS CONTRATADOS DOUBLE NOT NULL,
    DATOS CONSUMIDOS DOUBLE NOT NULL,
    4G BOOLEAN NOT NULL,
    VOZ CONTRATADA DOUBLE NOT NULL,
    VOZ CONSUMIDA DOUBLE NOT NULL,
    FRANJA VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    CLIENTE INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CLIENTE) REFERENCES PUBLIC.CLIENTES(ID)
)"; SQL statement:
INSERT INTO PUBLIC.CLIENTES(NOMBRE, APELLIDO, EDAD, DNI, EMAIL) VALUES
('Mónica', 'Garrido', 22, '12345678A', 'cortesm@dit.upm.es'),
('Alejandro', 'Docasar', 21, '12345678B', 'alejandrod@dit.upm.es'),
('Oscar', 'Vázquez', 21, '12345678C', 'oscarv@dit.upm.es'),
('Carlos', 'Padilla', 21, '12345678D', 'carlosp@dit.upm.es'),
('Héctor', 'Belló', 21, '12345678E', 'hectorb@dit.upm.es'),
('Fátima', 'García', 21, '12345678F', 'fatimag@dit.upm.es')


CREATE CACHED TABLE PUBLIC.TELEFONO(
    ID INTEGER AUTO_INCREMENT NOT NULL,
    COMPAÑIA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    IMPORTE DOUBLE NOT NULL,
    DATOS CONTRATADOS DOUBLE NOT NULL,
    DATOS CONSUMIDOS DOUBLE NOT NULL,
    4G BOOLEAN NOT NULL,
    VOZ CONTRATADA DOUBLE NOT NULL,
    VOZ CONSUMIDA DOUBLE NOT NULL,
    FRANJA VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    CLIENTE INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CLIENTE) REFERENCES PUBLIC.CLIENTES(ID)
) [42000-191]
2016-03-09 14:55:03 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Tabla "TELEFONO" no encontrada
Table "TELEFONO" not found; SQL statement:
INSERT INTO PUBLIC.TELEFONO(COMPAÑIA, NOMBRE, IMPORTE, DATOS, VOZ, FRANJA, FECHA, CLIENTE) VALUES
('Telefónica', 'Vive 13', 13, 1, 1.6, True, 0, 0, 'Tarde', '2016-01-02', 2),
('Telefónica', 'Vive 26', 26, 1.5, 1.7, True, 200, 150, 'Tarde', '2016-01-02', 1),
('Yoigo', 'La del 0', 9, 1.2, 1.7, True, 0, 10, 'Tarde', '2016-01-02', 4),
('Amena', 'tarifa 6.95', 6.95, 1, 1.8, True, 0, 30, 'Tarde', '2016-01-02', 5),
('Amena', 'tarifa 6.95', 6.95, 1, 0.9, True, 0, 7, 'Tarde', '2016-01-02', 3),
('Telefónica', 'Vive 13', 13, 1, 1.3, True, 0, 15, 'Tarde', '2016-01-02', 6) [42102-191]
2016-03-09 14:56:25 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Error de Sintaxis en sentencia SQL "INSERT INTO PUBLIC.CLIENTES(NOMBRE, APELLIDO, EDAD, DNI, EMAIL) VALUES
('Mónica', 'Garrido', 22, '12345678A', 'cortesm@dit.upm.es'),
('Alejandro', 'Docasar', 21, '12345678B', 'alejandrod@dit.upm.es'),
('Oscar', 'Vázquez', 21, '12345678C', 'oscarv@dit.upm.es'),
('Carlos', 'Padilla', 21, '12345678D', 'carlosp@dit.upm.es'),
('Héctor', 'Belló', 21, '12345678E', 'hectorb@dit.upm.es'),
('Fátima', 'García', 21, '12345678F', 'fatimag@dit.upm.es')


CREATE[*] CACHED TABLE PUBLIC.TELEFONO(
    ID INTEGER AUTO_INCREMENT NOT NULL,
    COMPAÑIA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    IMPORTE DOUBLE NOT NULL,
    DATOS CONTRATADOS DOUBLE NOT NULL,
    DATOS CONSUMIDOS DOUBLE NOT NULL,
    4G BOOLEAN NOT NULL,
    VOZ CONTRATADA DOUBLE NOT NULL,
    VOZ CONSUMIDA DOUBLE NOT NULL,
    FRANJA VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    CLIENTE INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CLIENTE) REFERENCES PUBLIC.CLIENTES(ID)
)"
Syntax error in SQL statement "INSERT INTO PUBLIC.CLIENTES(NOMBRE, APELLIDO, EDAD, DNI, EMAIL) VALUES
('Mónica', 'Garrido', 22, '12345678A', 'cortesm@dit.upm.es'),
('Alejandro', 'Docasar', 21, '12345678B', 'alejandrod@dit.upm.es'),
('Oscar', 'Vázquez', 21, '12345678C', 'oscarv@dit.upm.es'),
('Carlos', 'Padilla', 21, '12345678D', 'carlosp@dit.upm.es'),
('Héctor', 'Belló', 21, '12345678E', 'hectorb@dit.upm.es'),
('Fátima', 'García', 21, '12345678F', 'fatimag@dit.upm.es')


CREATE[*] CACHED TABLE PUBLIC.TELEFONO(
    ID INTEGER AUTO_INCREMENT NOT NULL,
    COMPAÑIA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    IMPORTE DOUBLE NOT NULL,
    DATOS CONTRATADOS DOUBLE NOT NULL,
    DATOS CONSUMIDOS DOUBLE NOT NULL,
    4G BOOLEAN NOT NULL,
    VOZ CONTRATADA DOUBLE NOT NULL,
    VOZ CONSUMIDA DOUBLE NOT NULL,
    FRANJA VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    CLIENTE INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CLIENTE) REFERENCES PUBLIC.CLIENTES(ID)
)"; SQL statement:
INSERT INTO PUBLIC.CLIENTES(NOMBRE, APELLIDO, EDAD, DNI, EMAIL) VALUES
('Mónica', 'Garrido', 22, '12345678A', 'cortesm@dit.upm.es'),
('Alejandro', 'Docasar', 21, '12345678B', 'alejandrod@dit.upm.es'),
('Oscar', 'Vázquez', 21, '12345678C', 'oscarv@dit.upm.es'),
('Carlos', 'Padilla', 21, '12345678D', 'carlosp@dit.upm.es'),
('Héctor', 'Belló', 21, '12345678E', 'hectorb@dit.upm.es'),
('Fátima', 'García', 21, '12345678F', 'fatimag@dit.upm.es')


CREATE CACHED TABLE PUBLIC.TELEFONO(
    ID INTEGER AUTO_INCREMENT NOT NULL,
    COMPAÑIA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    IMPORTE DOUBLE NOT NULL,
    DATOS CONTRATADOS DOUBLE NOT NULL,
    DATOS CONSUMIDOS DOUBLE NOT NULL,
    4G BOOLEAN NOT NULL,
    VOZ CONTRATADA DOUBLE NOT NULL,
    VOZ CONSUMIDA DOUBLE NOT NULL,
    FRANJA VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    CLIENTE INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CLIENTE) REFERENCES PUBLIC.CLIENTES(ID)
) [42000-191]
2016-03-09 14:56:25 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Tabla "TELEFONO" no encontrada
Table "TELEFONO" not found; SQL statement:
INSERT INTO PUBLIC.TELEFONO(COMPAÑIA, NOMBRE, IMPORTE, DATOS, VOZ, FRANJA, FECHA, CLIENTE) VALUES
('Telefónica', 'Vive 13', 13, 1, 1.6, True, 0, 0, 'Tarde', '2016-01-02', 2),
('Telefónica', 'Vive 26', 26, 1.5, 1.7, True, 200, 150, 'Tarde', '2016-01-02', 1),
('Yoigo', 'La del 0', 9, 1.2, 1.7, True, 0, 10, 'Tarde', '2016-01-02', 4),
('Amena', 'tarifa 6.95', 6.95, 1, 1.8, True, 0, 30, 'Tarde', '2016-01-02', 5),
('Amena', 'tarifa 6.95', 6.95, 1, 0.9, True, 0, 7, 'Tarde', '2016-01-02', 3),
('Telefónica', 'Vive 13', 13, 1, 1.3, True, 0, 15, 'Tarde', '2016-01-02', 6) [42102-191]
2016-03-09 14:57:53 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Tabla "CLIENTES" ya existe
Table "CLIENTES" already exists; SQL statement:
CREATE CACHED TABLE PUBLIC.CLIENTES(
    ID INTEGER AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(20) NOT NULL,
    APELLIDO VARCHAR(20) NOT NULL,
    EDAD INTEGER NOT NULL,
    DNI VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
) [42101-191]
2016-03-09 14:57:53 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Tipo de dato desconocido : "CONTRATADOS"
Unknown data type: "CONTRATADOS"; SQL statement:
CREATE CACHED TABLE PUBLIC.TELEFONO(
    ID INTEGER AUTO_INCREMENT NOT NULL,
    COMPAÑIA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    IMPORTE DOUBLE NOT NULL,
    DATOS CONTRATADOS DOUBLE NOT NULL,
    DATOS CONSUMIDOS DOUBLE NOT NULL,
    4G BOOLEAN NOT NULL,
    VOZ CONTRATADA DOUBLE NOT NULL,
    VOZ CONSUMIDA DOUBLE NOT NULL,
    FRANJA VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    CLIENTE INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CLIENTE) REFERENCES PUBLIC.CLIENTES(ID)
) [50004-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4059)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3922)
	at org.h2.command.Parser.parseCreateTable(Parser.java:5864)
	at org.h2.command.Parser.parseCreate(Parser.java:4217)
	at org.h2.command.Parser.parsePrepared(Parser.java:360)
	at org.h2.command.Parser.parse(Parser.java:315)
	at org.h2.command.Parser.parse(Parser.java:287)
	at org.h2.command.Parser.prepareCommand(Parser.java:252)
	at org.h2.engine.Session.prepareLocal(Session.java:560)
	at org.h2.engine.Session.prepareCommand(Session.java:501)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1388)
	at org.h2.server.web.WebApp.query(WebApp.java:1061)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1023)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1010)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2016-03-09 14:57:53 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Tabla "TELEFONO" no encontrada
Table "TELEFONO" not found; SQL statement:
INSERT INTO PUBLIC.TELEFONO(COMPAÑIA, NOMBRE, IMPORTE, DATOS, VOZ, FRANJA, FECHA, CLIENTE) VALUES
('Telefónica', 'Vive 13', 13, 1, 1.6, True, 0, 0, 'Tarde', '2016-01-02', 2),
('Telefónica', 'Vive 26', 26, 1.5, 1.7, True, 200, 150, 'Tarde', '2016-01-02', 1),
('Yoigo', 'La del 0', 9, 1.2, 1.7, True, 0, 10, 'Tarde', '2016-01-02', 4),
('Amena', 'tarifa 6.95', 6.95, 1, 1.8, True, 0, 30, 'Tarde', '2016-01-02', 5),
('Amena', 'tarifa 6.95', 6.95, 1, 0.9, True, 0, 7, 'Tarde', '2016-01-02', 3),
('Telefónica', 'Vive 13', 13, 1, 1.3, True, 0, 15, 'Tarde', '2016-01-02', 6) [42102-191]
2016-03-09 14:58:35 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Tabla "CLIENTES" ya existe
Table "CLIENTES" already exists; SQL statement:
CREATE CACHED TABLE PUBLIC.CLIENTES(
    ID INTEGER AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(20) NOT NULL,
    APELLIDO VARCHAR(20) NOT NULL,
    EDAD INTEGER NOT NULL,
    DNI VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
) [42101-191]
2016-03-09 14:58:35 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Tipo de dato desconocido : "CONTRATADOS"
Unknown data type: "CONTRATADOS"; SQL statement:
CREATE CACHED TABLE PUBLIC.TELEFONO(
    ID INTEGER AUTO_INCREMENT NOT NULL,
    COMPAÑIA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    IMPORTE DOUBLE NOT NULL,
    DATOS CONTRATADOS DOUBLE NOT NULL,
    DATOS CONSUMIDOS DOUBLE NOT NULL,
    4G BOOLEAN NOT NULL,
    VOZ CONTRATADA DOUBLE NOT NULL,
    VOZ CONSUMIDA DOUBLE NOT NULL,
    FRANJA VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    CLIENTE INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CLIENTE) REFERENCES PUBLIC.CLIENTES(ID)
) [50004-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4059)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3922)
	at org.h2.command.Parser.parseCreateTable(Parser.java:5864)
	at org.h2.command.Parser.parseCreate(Parser.java:4217)
	at org.h2.command.Parser.parsePrepared(Parser.java:360)
	at org.h2.command.Parser.parse(Parser.java:315)
	at org.h2.command.Parser.parse(Parser.java:287)
	at org.h2.command.Parser.prepareCommand(Parser.java:252)
	at org.h2.engine.Session.prepareLocal(Session.java:560)
	at org.h2.engine.Session.prepareCommand(Session.java:501)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1388)
	at org.h2.server.web.WebApp.query(WebApp.java:1061)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1023)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1010)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2016-03-09 14:58:35 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Tabla "TELEFONO" no encontrada
Table "TELEFONO" not found; SQL statement:
INSERT INTO PUBLIC.TELEFONO(COMPAÑIA, NOMBRE, IMPORTE, DATOS, VOZ, FRANJA, FECHA, CLIENTE) VALUES
('Telefónica', 'Vive 13', 13, 1, 1.6, True, 0, 0, 'Tarde', '2016-01-02', 2),
('Telefónica', 'Vive 26', 26, 1.5, 1.7, True, 200, 150, 'Tarde', '2016-01-02', 1),
('Yoigo', 'La del 0', 9, 1.2, 1.7, True, 0, 10, 'Tarde', '2016-01-02', 4),
('Amena', 'tarifa 6.95', 6.95, 1, 1.8, True, 0, 30, 'Tarde', '2016-01-02', 5),
('Amena', 'tarifa 6.95', 6.95, 1, 0.9, True, 0, 7, 'Tarde', '2016-01-02', 3),
('Telefónica', 'Vive 13', 13, 1, 1.3, True, 0, 15, 'Tarde', '2016-01-02', 6) [42102-191]
2016-03-09 14:59:04 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Tipo de dato desconocido : "CONTRATADOS"
Unknown data type: "CONTRATADOS"; SQL statement:
CREATE CACHED TABLE PUBLIC.TELEFONO(
    ID INTEGER AUTO_INCREMENT NOT NULL,
    COMPAÑIA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    IMPORTE DOUBLE NOT NULL,
    DATOS CONTRATADOS DOUBLE NOT NULL,
    DATOS CONSUMIDOS DOUBLE NOT NULL,
    4G BOOLEAN NOT NULL,
    VOZ CONTRATADA DOUBLE NOT NULL,
    VOZ CONSUMIDA DOUBLE NOT NULL,
    FRANJA VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    CLIENTE INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CLIENTE) REFERENCES PUBLIC.CLIENTES(ID)
) [50004-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4059)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3922)
	at org.h2.command.Parser.parseCreateTable(Parser.java:5864)
	at org.h2.command.Parser.parseCreate(Parser.java:4217)
	at org.h2.command.Parser.parsePrepared(Parser.java:360)
	at org.h2.command.Parser.parse(Parser.java:315)
	at org.h2.command.Parser.parse(Parser.java:287)
	at org.h2.command.Parser.prepareCommand(Parser.java:252)
	at org.h2.engine.Session.prepareLocal(Session.java:560)
	at org.h2.engine.Session.prepareCommand(Session.java:501)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1388)
	at org.h2.server.web.WebApp.query(WebApp.java:1061)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1023)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1010)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2016-03-09 14:59:04 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Tabla "TELEFONO" no encontrada
Table "TELEFONO" not found; SQL statement:
INSERT INTO PUBLIC.TELEFONO(COMPAÑIA, NOMBRE, IMPORTE, DATOS, VOZ, FRANJA, FECHA, CLIENTE) VALUES
('Telefónica', 'Vive 13', 13, 1, 1.6, True, 0, 0, 'Tarde', '2016-01-02', 2),
('Telefónica', 'Vive 26', 26, 1.5, 1.7, True, 200, 150, 'Tarde', '2016-01-02', 1),
('Yoigo', 'La del 0', 9, 1.2, 1.7, True, 0, 10, 'Tarde', '2016-01-02', 4),
('Amena', 'tarifa 6.95', 6.95, 1, 1.8, True, 0, 30, 'Tarde', '2016-01-02', 5),
('Amena', 'tarifa 6.95', 6.95, 1, 0.9, True, 0, 7, 'Tarde', '2016-01-02', 3),
('Telefónica', 'Vive 13', 13, 1, 1.3, True, 0, 15, 'Tarde', '2016-01-02', 6) [42102-191]
2016-03-09 15:00:51 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Error de Sintaxis en sentencia SQL "CREATE CACHED TABLE PUBLIC.TELEFONO(
    ID INTEGER AUTO_INCREMENT NOT NULL,
    COMPAÑIA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    IMPORTE DOUBLE NOT NULL,
    DATOS_CONTRATADOS DOUBLE NOT NULL,
    DATOS_CONSUMIDOS DOUBLE NOT NULL,
    4[*]G BOOLEAN NOT NULL,
    VOZ_CONTRATADA DOUBLE NOT NULL,
    VOZ_CONSUMIDA DOUBLE NOT NULL,
    FRANJA VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    CLIENTE INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CLIENTE) REFERENCES PUBLIC.CLIENTES(ID)
)"; se esperaba "identifier"
Syntax error in SQL statement "CREATE CACHED TABLE PUBLIC.TELEFONO(
    ID INTEGER AUTO_INCREMENT NOT NULL,
    COMPAÑIA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    IMPORTE DOUBLE NOT NULL,
    DATOS_CONTRATADOS DOUBLE NOT NULL,
    DATOS_CONSUMIDOS DOUBLE NOT NULL,
    4[*]G BOOLEAN NOT NULL,
    VOZ_CONTRATADA DOUBLE NOT NULL,
    VOZ_CONSUMIDA DOUBLE NOT NULL,
    FRANJA VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    CLIENTE INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CLIENTE) REFERENCES PUBLIC.CLIENTES(ID)
)"; expected "identifier"; SQL statement:
CREATE CACHED TABLE PUBLIC.TELEFONO(
    ID INTEGER AUTO_INCREMENT NOT NULL,
    COMPAÑIA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    IMPORTE DOUBLE NOT NULL,
    DATOS_CONTRATADOS DOUBLE NOT NULL,
    DATOS_CONSUMIDOS DOUBLE NOT NULL,
    4G BOOLEAN NOT NULL,
    VOZ_CONTRATADA DOUBLE NOT NULL,
    VOZ_CONSUMIDA DOUBLE NOT NULL,
    FRANJA VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    CLIENTE INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CLIENTE) REFERENCES PUBLIC.CLIENTES(ID)
) [42001-191]
2016-03-09 15:00:51 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Tabla "TELEFONO" no encontrada
Table "TELEFONO" not found; SQL statement:
INSERT INTO PUBLIC.TELEFONO(COMPAÑIA, NOMBRE, IMPORTE, DATOS_CONTRATADOS, DATOS_CONSUMIDOS, VOZ_CONTRATADA, VOZ_CONSUMIDA, FRANJA, FECHA, CLIENTE) VALUES
('Telefónica', 'Vive 13', 13, 1, 1.6, True, 0, 0, 'Tarde', '2016-01-02', 2),
('Telefónica', 'Vive 26', 26, 1.5, 1.7, True, 200, 150, 'Tarde', '2016-01-02', 1),
('Yoigo', 'La del 0', 9, 1.2, 1.7, True, 0, 10, 'Tarde', '2016-01-02', 4),
('Amena', 'tarifa 6.95', 6.95, 1, 1.8, True, 0, 30, 'Tarde', '2016-01-02', 5),
('Amena', 'tarifa 6.95', 6.95, 1, 0.9, True, 0, 7, 'Tarde', '2016-01-02', 3),
('Telefónica', 'Vive 13', 13, 1, 1.3, True, 0, 15, 'Tarde', '2016-01-02', 6) [42102-191]
2016-03-09 15:09:53 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Error de Sintaxis en sentencia SQL "CREATE CACHED TABLE PUBLIC.TELEFONO(
    ID INTEGER AUTO_INCREMENT NOT NULL,
    COMPAÑIA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    IMPORTE DOUBLE NOT NULL,
    DATOS_CONTRATADOS DOUBLE NOT NULL,
    DATOS_CONSUMIDOS DOUBLE NOT NULL,
    4[*]G BOOLEAN NOT NULL,
    VOZ_CONTRATADA DOUBLE NOT NULL,
    VOZ_CONSUMIDA DOUBLE NOT NULL,
    FRANJA VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    CLIENTE INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CLIENTE) REFERENCES PUBLIC.CLIENTES(ID)
)"; se esperaba "identifier"
Syntax error in SQL statement "CREATE CACHED TABLE PUBLIC.TELEFONO(
    ID INTEGER AUTO_INCREMENT NOT NULL,
    COMPAÑIA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    IMPORTE DOUBLE NOT NULL,
    DATOS_CONTRATADOS DOUBLE NOT NULL,
    DATOS_CONSUMIDOS DOUBLE NOT NULL,
    4[*]G BOOLEAN NOT NULL,
    VOZ_CONTRATADA DOUBLE NOT NULL,
    VOZ_CONSUMIDA DOUBLE NOT NULL,
    FRANJA VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    CLIENTE INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CLIENTE) REFERENCES PUBLIC.CLIENTES(ID)
)"; expected "identifier"; SQL statement:
CREATE CACHED TABLE PUBLIC.TELEFONO(
    ID INTEGER AUTO_INCREMENT NOT NULL,
    COMPAÑIA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    IMPORTE DOUBLE NOT NULL,
    DATOS_CONTRATADOS DOUBLE NOT NULL,
    DATOS_CONSUMIDOS DOUBLE NOT NULL,
    4G BOOLEAN NOT NULL,
    VOZ_CONTRATADA DOUBLE NOT NULL,
    VOZ_CONSUMIDA DOUBLE NOT NULL,
    FRANJA VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    CLIENTE INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CLIENTE) REFERENCES PUBLIC.CLIENTES(ID)
) [42001-191]
2016-03-09 15:09:53 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Tabla "TELEFONO" no encontrada
Table "TELEFONO" not found; SQL statement:
INSERT INTO PUBLIC.TELEFONO(COMPAÑIA, NOMBRE, IMPORTE, DATOS_CONTRATADOS, DATOS_CONSUMIDOS, VOZ_CONTRATADA, VOZ_CONSUMIDA, FRANJA, FECHA, CLIENTE) VALUES
('Telefónica', 'Vive 13', 13, 1, 1.6, True, 0, 0, 'Tarde', '2016-01-02', 2),
('Telefónica', 'Vive 26', 26, 1.5, 1.7, True, 200, 150, 'Tarde', '2016-01-02', 1),
('Yoigo', 'La del 0', 9, 1.2, 1.7, True, 0, 10, 'Tarde', '2016-01-02', 4),
('Amena', 'tarifa 6.95', 6.95, 1, 1.8, True, 0, 30, 'Tarde', '2016-01-02', 5),
('Amena', 'tarifa 6.95', 6.95, 1, 0.9, True, 0, 7, 'Tarde', '2016-01-02', 3),
('Telefónica', 'Vive 13', 13, 1, 1.3, True, 0, 15, 'Tarde', '2016-01-02', 6) [42102-191]
2016-03-09 15:09:53 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Tabla "TELEFONO" no encontrada
Table "TELEFONO" not found; SQL statement:
ALTER TABLE PUBLIC.TELEFONO
    ADD FOREIGN KEY (CLIENTE) 
    REFERENCES PUBLIC.CLIENTE(ID) [42102-191]
2016-03-09 15:14:43 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Error de Sintaxis en sentencia SQL "CREATE CACHED TABLE PUBLIC.TELEFONO(
    ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    COMPAÑIA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    IMPORTE DOUBLE NOT NULL,
    DATOS_CONTRATADOS DOUBLE NOT NULL,
    DATOS_CONSUMIDOS DOUBLE NOT NULL,
    4[*]G BOOLEAN NOT NULL,
    VOZ_CONTRATADA DOUBLE NOT NULL,
    VOZ_CONSUMIDA DOUBLE NOT NULL,
    FRANJA VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    FOREIGN KEY (CLIENTE)
    REFERENCES PUBLIC.CLIENTES(ID)
)"; se esperaba "identifier"
Syntax error in SQL statement "CREATE CACHED TABLE PUBLIC.TELEFONO(
    ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    COMPAÑIA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    IMPORTE DOUBLE NOT NULL,
    DATOS_CONTRATADOS DOUBLE NOT NULL,
    DATOS_CONSUMIDOS DOUBLE NOT NULL,
    4[*]G BOOLEAN NOT NULL,
    VOZ_CONTRATADA DOUBLE NOT NULL,
    VOZ_CONSUMIDA DOUBLE NOT NULL,
    FRANJA VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    FOREIGN KEY (CLIENTE)
    REFERENCES PUBLIC.CLIENTES(ID)
)"; expected "identifier"; SQL statement:
CREATE CACHED TABLE PUBLIC.TELEFONO(
    ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    COMPAÑIA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    IMPORTE DOUBLE NOT NULL,
    DATOS_CONTRATADOS DOUBLE NOT NULL,
    DATOS_CONSUMIDOS DOUBLE NOT NULL,
    4G BOOLEAN NOT NULL,
    VOZ_CONTRATADA DOUBLE NOT NULL,
    VOZ_CONSUMIDA DOUBLE NOT NULL,
    FRANJA VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    FOREIGN KEY (CLIENTE)
    REFERENCES PUBLIC.CLIENTES(ID)
) [42001-191]
2016-03-09 15:14:43 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Tabla "TELEFONO" no encontrada
Table "TELEFONO" not found; SQL statement:
INSERT INTO PUBLIC.TELEFONO(COMPAÑIA, NOMBRE, IMPORTE, DATOS_CONTRATADOS, DATOS_CONSUMIDOS, VOZ_CONTRATADA, VOZ_CONSUMIDA, FRANJA, FECHA, CLIENTE) VALUES
('Telefónica', 'Vive 13', 13, 1, 1.6, True, 0, 0, 'Tarde', '2016-01-02', 2),
('Telefónica', 'Vive 26', 26, 1.5, 1.7, True, 200, 150, 'Tarde', '2016-01-02', 1),
('Yoigo', 'La del 0', 9, 1.2, 1.7, True, 0, 10, 'Tarde', '2016-01-02', 4),
('Amena', 'tarifa 6.95', 6.95, 1, 1.8, True, 0, 30, 'Tarde', '2016-01-02', 5),
('Amena', 'tarifa 6.95', 6.95, 1, 0.9, True, 0, 7, 'Tarde', '2016-01-02', 3),
('Telefónica', 'Vive 13', 13, 1, 1.3, True, 0, 15, 'Tarde', '2016-01-02', 6) [42102-191]
2016-03-09 15:19:05 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Error de Sintaxis en sentencia SQL "CREATE CACHED TABLE PUBLIC.TELEFONO(
    ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    COMPAÑIA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    IMPORTE DOUBLE NOT NULL,
    DATOS_CONTRATADOS DOUBLE NOT NULL,
    DATOS_CONSUMIDOS DOUBLE NOT NULL,
    4[*]G BOOLEAN NOT NULL,
    VOZ_CONTRATADA DOUBLE NOT NULL,
    VOZ_CONSUMIDA DOUBLE NOT NULL,
    FRANJA VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    CLIENTE INTEGER FOREIGN KEY REFERENCES PUBLIC.CLIENTES(ID)
)"; se esperaba "identifier"
Syntax error in SQL statement "CREATE CACHED TABLE PUBLIC.TELEFONO(
    ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    COMPAÑIA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    IMPORTE DOUBLE NOT NULL,
    DATOS_CONTRATADOS DOUBLE NOT NULL,
    DATOS_CONSUMIDOS DOUBLE NOT NULL,
    4[*]G BOOLEAN NOT NULL,
    VOZ_CONTRATADA DOUBLE NOT NULL,
    VOZ_CONSUMIDA DOUBLE NOT NULL,
    FRANJA VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    CLIENTE INTEGER FOREIGN KEY REFERENCES PUBLIC.CLIENTES(ID)
)"; expected "identifier"; SQL statement:
CREATE CACHED TABLE PUBLIC.TELEFONO(
    ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    COMPAÑIA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    IMPORTE DOUBLE NOT NULL,
    DATOS_CONTRATADOS DOUBLE NOT NULL,
    DATOS_CONSUMIDOS DOUBLE NOT NULL,
    4G BOOLEAN NOT NULL,
    VOZ_CONTRATADA DOUBLE NOT NULL,
    VOZ_CONSUMIDA DOUBLE NOT NULL,
    FRANJA VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    CLIENTE INTEGER FOREIGN KEY REFERENCES PUBLIC.CLIENTES(ID)
) [42001-191]
2016-03-09 15:19:05 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Tabla "TELEFONO" no encontrada
Table "TELEFONO" not found; SQL statement:
INSERT INTO PUBLIC.TELEFONO(COMPAÑIA, NOMBRE, IMPORTE, DATOS_CONTRATADOS, DATOS_CONSUMIDOS, VOZ_CONTRATADA, VOZ_CONSUMIDA, FRANJA, FECHA, CLIENTE) VALUES
('Telefónica', 'Vive 13', 13, 1, 1.6, True, 0, 0, 'Tarde', '2016-01-02', 2),
('Telefónica', 'Vive 26', 26, 1.5, 1.7, True, 200, 150, 'Tarde', '2016-01-02', 1),
('Yoigo', 'La del 0', 9, 1.2, 1.7, True, 0, 10, 'Tarde', '2016-01-02', 4),
('Amena', 'tarifa 6.95', 6.95, 1, 1.8, True, 0, 30, 'Tarde', '2016-01-02', 5),
('Amena', 'tarifa 6.95', 6.95, 1, 0.9, True, 0, 7, 'Tarde', '2016-01-02', 3),
('Telefónica', 'Vive 13', 13, 1, 1.3, True, 0, 15, 'Tarde', '2016-01-02', 6) [42102-191]
2016-03-09 15:24:33 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Error de Sintaxis en sentencia SQL "CREATE CACHED TABLE PUBLIC.TELEFONO(
    ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    COMPAÑIA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    IMPORTE DOUBLE NOT NULL,
    DATOS_CONTRATADOS DOUBLE NOT NULL,
    DATOS_CONSUMIDOS DOUBLE NOT NULL,
    4[*]G BOOLEAN NOT NULL,
    VOZ_CONTRATADA DOUBLE NOT NULL,
    VOZ_CONSUMIDA DOUBLE NOT NULL,
    FRANJA VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    CLIENTE INTEGER FOREIGN KEY
)"; se esperaba "identifier"
Syntax error in SQL statement "CREATE CACHED TABLE PUBLIC.TELEFONO(
    ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    COMPAÑIA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    IMPORTE DOUBLE NOT NULL,
    DATOS_CONTRATADOS DOUBLE NOT NULL,
    DATOS_CONSUMIDOS DOUBLE NOT NULL,
    4[*]G BOOLEAN NOT NULL,
    VOZ_CONTRATADA DOUBLE NOT NULL,
    VOZ_CONSUMIDA DOUBLE NOT NULL,
    FRANJA VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    CLIENTE INTEGER FOREIGN KEY
)"; expected "identifier"; SQL statement:
CREATE CACHED TABLE PUBLIC.TELEFONO(
    ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    COMPAÑIA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    IMPORTE DOUBLE NOT NULL,
    DATOS_CONTRATADOS DOUBLE NOT NULL,
    DATOS_CONSUMIDOS DOUBLE NOT NULL,
    4G BOOLEAN NOT NULL,
    VOZ_CONTRATADA DOUBLE NOT NULL,
    VOZ_CONSUMIDA DOUBLE NOT NULL,
    FRANJA VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    CLIENTE INTEGER FOREIGN KEY
) [42001-191]
2016-03-09 15:24:33 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Tabla "TELEFONO" no encontrada
Table "TELEFONO" not found; SQL statement:
INSERT INTO PUBLIC.TELEFONO(COMPAÑIA, NOMBRE, IMPORTE, DATOS_CONTRATADOS, DATOS_CONSUMIDOS, VOZ_CONTRATADA, VOZ_CONSUMIDA, FRANJA, FECHA, CLIENTE) VALUES
('Telefónica', 'Vive 13', 13, 1, 1.6, True, 0, 0, 'Tarde', '2016-01-02', 2),
('Telefónica', 'Vive 26', 26, 1.5, 1.7, True, 200, 150, 'Tarde', '2016-01-02', 1),
('Yoigo', 'La del 0', 9, 1.2, 1.7, True, 0, 10, 'Tarde', '2016-01-02', 4),
('Amena', 'tarifa 6.95', 6.95, 1, 1.8, True, 0, 30, 'Tarde', '2016-01-02', 5),
('Amena', 'tarifa 6.95', 6.95, 1, 0.9, True, 0, 7, 'Tarde', '2016-01-02', 3),
('Telefónica', 'Vive 13', 13, 1, 1.3, True, 0, 15, 'Tarde', '2016-01-02', 6) [42102-191]
2016-03-09 15:24:33 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Tabla "TELEFONO" no encontrada
Table "TELEFONO" not found; SQL statement:
ALTER TABLE PUBLIC.TELEFONO ADD FOREIGN KEY (CLIENTE) REFERENCES PUBLIC.CLIENTE(CLIENTE) [42102-191]
2016-03-09 15:27:15 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Error de Sintaxis en sentencia SQL "CREATE CACHED TABLE PUBLIC.TELEFONO(
    ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    COMPAÑIA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    IMPORTE DOUBLE NOT NULL,
    DATOS_CONTRATADOS DOUBLE NOT NULL,
    DATOS_CONSUMIDOS DOUBLE NOT NULL,
    4[*]G BOOLEAN NOT NULL,
    VOZ_CONTRATADA DOUBLE NOT NULL,
    VOZ_CONSUMIDA DOUBLE NOT NULL,
    FRANJA VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    CLIENTE INTEGER
)"; se esperaba "identifier"
Syntax error in SQL statement "CREATE CACHED TABLE PUBLIC.TELEFONO(
    ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    COMPAÑIA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    IMPORTE DOUBLE NOT NULL,
    DATOS_CONTRATADOS DOUBLE NOT NULL,
    DATOS_CONSUMIDOS DOUBLE NOT NULL,
    4[*]G BOOLEAN NOT NULL,
    VOZ_CONTRATADA DOUBLE NOT NULL,
    VOZ_CONSUMIDA DOUBLE NOT NULL,
    FRANJA VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    CLIENTE INTEGER
)"; expected "identifier"; SQL statement:
CREATE CACHED TABLE PUBLIC.TELEFONO(
    ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    COMPAÑIA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    IMPORTE DOUBLE NOT NULL,
    DATOS_CONTRATADOS DOUBLE NOT NULL,
    DATOS_CONSUMIDOS DOUBLE NOT NULL,
    4G BOOLEAN NOT NULL,
    VOZ_CONTRATADA DOUBLE NOT NULL,
    VOZ_CONSUMIDA DOUBLE NOT NULL,
    FRANJA VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    CLIENTE INTEGER
) [42001-191]
2016-03-09 15:27:15 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Tabla "TELEFONO" no encontrada
Table "TELEFONO" not found; SQL statement:
INSERT INTO PUBLIC.TELEFONO(COMPAÑIA, NOMBRE, IMPORTE, DATOS_CONTRATADOS, DATOS_CONSUMIDOS, VOZ_CONTRATADA, VOZ_CONSUMIDA, FRANJA, FECHA, CLIENTE) VALUES
('Telefónica', 'Vive 13', 13, 1, 1.6, True, 0, 0, 'Tarde', '2016-01-02', 2),
('Telefónica', 'Vive 26', 26, 1.5, 1.7, True, 200, 150, 'Tarde', '2016-01-02', 1),
('Yoigo', 'La del 0', 9, 1.2, 1.7, True, 0, 10, 'Tarde', '2016-01-02', 4),
('Amena', 'tarifa 6.95', 6.95, 1, 1.8, True, 0, 30, 'Tarde', '2016-01-02', 5),
('Amena', 'tarifa 6.95', 6.95, 1, 0.9, True, 0, 7, 'Tarde', '2016-01-02', 3),
('Telefónica', 'Vive 13', 13, 1, 1.3, True, 0, 15, 'Tarde', '2016-01-02', 6) [42102-191]
2016-03-09 15:27:15 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Tabla "TELEFONO" no encontrada
Table "TELEFONO" not found; SQL statement:
ALTER TABLE PUBLIC.TELEFONO ADD FOREIGN KEY (CLIENTE) REFERENCES PUBLIC.CLIENTE(CLIENTE) [42102-191]
2016-03-09 15:31:29 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Error de Sintaxis en sentencia SQL "CREATE CACHED TABLE PUBLIC.TELEFONO(
    ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    COMPAÑIA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    IMPORTE DOUBLE NOT NULL,
    DATOS_CONTRATADOS DOUBLE NOT NULL,
    DATOS_CONSUMIDOS DOUBLE NOT NULL,
    LTE BOOLEAN NOT NULL,
    VOZ_CONTRATADA DOUBLE NOT NULL,
    VOZ_CONSUMIDA DOUBLE NOT NULL,
    FRANJA VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    CLIENTE INTEGER FOREIGN[*] KEY
)"; se esperaba "(, FOR, UNSIGNED, NOT, NULL, AS, DEFAULT, GENERATED, NOT, NULL, AUTO_INCREMENT, BIGSERIAL, SERIAL, IDENTITY, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, PRIMARY, UNIQUE, NOT, NULL, CHECK, REFERENCES, ,, )"
Syntax error in SQL statement "CREATE CACHED TABLE PUBLIC.TELEFONO(
    ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    COMPAÑIA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    IMPORTE DOUBLE NOT NULL,
    DATOS_CONTRATADOS DOUBLE NOT NULL,
    DATOS_CONSUMIDOS DOUBLE NOT NULL,
    LTE BOOLEAN NOT NULL,
    VOZ_CONTRATADA DOUBLE NOT NULL,
    VOZ_CONSUMIDA DOUBLE NOT NULL,
    FRANJA VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    CLIENTE INTEGER FOREIGN[*] KEY
)"; expected "(, FOR, UNSIGNED, NOT, NULL, AS, DEFAULT, GENERATED, NOT, NULL, AUTO_INCREMENT, BIGSERIAL, SERIAL, IDENTITY, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, PRIMARY, UNIQUE, NOT, NULL, CHECK, REFERENCES, ,, )"; SQL statement:
CREATE CACHED TABLE PUBLIC.TELEFONO(
    ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    COMPAÑIA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    IMPORTE DOUBLE NOT NULL,
    DATOS_CONTRATADOS DOUBLE NOT NULL,
    DATOS_CONSUMIDOS DOUBLE NOT NULL,
    LTE BOOLEAN NOT NULL,
    VOZ_CONTRATADA DOUBLE NOT NULL,
    VOZ_CONSUMIDA DOUBLE NOT NULL,
    FRANJA VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    CLIENTE INTEGER FOREIGN KEY
) [42001-191]
2016-03-09 15:31:29 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Tabla "TELEFONO" no encontrada
Table "TELEFONO" not found; SQL statement:
INSERT INTO PUBLIC.TELEFONO(COMPAÑIA, NOMBRE, IMPORTE, DATOS_CONTRATADOS, DATOS_CONSUMIDOS, LTE, VOZ_CONTRATADA, VOZ_CONSUMIDA, FRANJA, FECHA, CLIENTE) VALUES
('Telefónica', 'Vive 13', 13, 1, 1.6, True, 0, 0, 'Tarde', '2016-01-02', 2),
('Telefónica', 'Vive 26', 26, 1.5, 1.7, True, 200, 150, 'Tarde', '2016-01-02', 1),
('Yoigo', 'La del 0', 9, 1.2, 1.7, True, 0, 10, 'Tarde', '2016-01-02', 4),
('Amena', 'tarifa 6.95', 6.95, 1, 1.8, True, 0, 30, 'Tarde', '2016-01-02', 5),
('Amena', 'tarifa 6.95', 6.95, 1, 0.9, True, 0, 7, 'Tarde', '2016-01-02', 3),
('Telefónica', 'Vive 13', 13, 1, 1.3, True, 0, 15, 'Tarde', '2016-01-02', 6) [42102-191]
2016-03-09 15:31:29 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Tabla "TELEFONO" no encontrada
Table "TELEFONO" not found; SQL statement:
ALTER TABLE PUBLIC.TELEFONO ADD FOREIGN KEY (CLIENTE) REFERENCES PUBLIC.CLIENTE(CLIENTE) [42102-191]
2016-03-09 15:33:35 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Tabla "CLIENTE" no encontrada
Table "CLIENTE" not found; SQL statement:
ALTER TABLE PUBLIC.TELEFONO ADD FOREIGN KEY (CLIENTE) REFERENCES PUBLIC.CLIENTE(CLIENTE) [42102-191]
2016-03-09 15:34:54 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Columna "CLIENTE" no encontrada
Column "CLIENTE" not found; SQL statement:
ALTER TABLE PUBLIC.TELEFONO ADD FOREIGN KEY (CLIENTE) REFERENCES PUBLIC.CLIENTES(CLIENTE) [42122-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:680)
	at org.h2.table.IndexColumn.mapColumns(IndexColumn.java:74)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:212)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:72)
	at org.h2.command.CommandContainer.update(CommandContainer.java:98)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1388)
	at org.h2.server.web.WebApp.query(WebApp.java:1061)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1023)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1010)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2016-03-09 16:24:04 jdbc[11]: exception
org.h2.jdbc.JdbcSQLException: Error de Sintaxis en sentencia SQL "SELECT * FROM *[*]"; se esperaba "identifier"
Syntax error in SQL statement "SELECT * FROM *[*]"; expected "identifier"; SQL statement:
SELECT * FROM * [42001-191]
2016-03-09 16:56:04 database: flush
org.h2.message.DbException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/hector/workspace/ISST-Grupo09-iFactura/lib/iFacturaDB.mv.db [1.4.191/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/hector/workspace/ISST-Grupo09-iFactura/lib/iFacturaDB.mv.db [1.4.191/7]" [50000-191]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:373)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:356)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2460)
	at org.h2.engine.Database.open(Database.java:692)
	at org.h2.engine.Database.openDatabase(Database.java:270)
	at org.h2.engine.Database.<init>(Database.java:264)
	at org.h2.engine.Engine.openSession(Engine.java:65)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at Conexion.<init>(Conexion.java:17)
	at Sistema.main(Sistema.java:5)
Caused by: org.h2.jdbc.JdbcSQLException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/hector/workspace/ISST-Grupo09-iFactura/lib/iFacturaDB.mv.db [1.4.191/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/hector/workspace/ISST-Grupo09-iFactura/lib/iFacturaDB.mv.db [1.4.191/7]" [50000-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 25 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/hector/workspace/ISST-Grupo09-iFactura/lib/iFacturaDB.mv.db [1.4.191/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
	... 20 more
2016-03-09 16:56:28 database: flush
org.h2.message.DbException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/hector/workspace/ISST-Grupo09-iFactura/lib/iFacturaDB.mv.db [1.4.191/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/hector/workspace/ISST-Grupo09-iFactura/lib/iFacturaDB.mv.db [1.4.191/7]" [50000-191]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:373)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:356)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2460)
	at org.h2.engine.Database.open(Database.java:692)
	at org.h2.engine.Database.openDatabase(Database.java:270)
	at org.h2.engine.Database.<init>(Database.java:264)
	at org.h2.engine.Engine.openSession(Engine.java:65)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at Conexion.<init>(Conexion.java:17)
	at Sistema.main(Sistema.java:5)
Caused by: org.h2.jdbc.JdbcSQLException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/hector/workspace/ISST-Grupo09-iFactura/lib/iFacturaDB.mv.db [1.4.191/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/hector/workspace/ISST-Grupo09-iFactura/lib/iFacturaDB.mv.db [1.4.191/7]" [50000-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 25 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/hector/workspace/ISST-Grupo09-iFactura/lib/iFacturaDB.mv.db [1.4.191/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
	... 20 more
